version: '3.8'

services:
  web:
    image: php:8.1-apache
    container_name: app-web
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db
      - DB_NAME=calendar_app
      - DB_USER=user
      - DB_PASS=pass
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: app-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: calendar_app
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
